### PR TITLE
Generate default configuration by default

### PR DESCRIPTION
**Pull request by jcwillox**
As many other tools do winfetch should generate its default configuration by default. Currently, winfetch generates an empty config at `~/.config/winfetch/config.ps1` and shows all info segments if that file is empty. This PR changes it so that when running winfetch if the `config.ps1` file is empty (or doesn't exist) we automatically download the default configuration file and continue.

The `-genconf` parameter is still available, as before, it will download the config and exit. This functionality will be used to generate the config during the scoop installation process as well (it will do nothing if it's not empty).

I also removed the if statement around `$config = . $configPath` because it is redundant as we already ensure the config file exists before this, and if it's empty then we fallback to the `$baseConfig` anyway.

### CODE REVIEW

**Comment by rashil2000** [comment]
I don't think it's wise to force download anything without user's specific action (that too on the first run itself). It's not a good practice. What if I'm not connected to the internet (or outgoing requests are blocked)? The script should (and does) work independently.
The genconf parameter actually makes sense, because it requires explicit approval by user (and it's fair to assume that it'll need internet for that).

**Comment by rashil2000** [comment]
What you can do instead is follow Neofetch, and include the default config content string in winfetch.ps1 itself, and then generate a file with those string contents.

**Comment by jcwillox** [comment]
Yeah, I was thinking that too, kinda undecided on the idea though. By using the web request we can separate the `config.ps1` and `winfetch.ps1`, but by including it inside `winfetch.ps1` we don't have to make a web request, which simplifies a couple of things and maybe more reliable?

**Comment by rashil2000** [comment]
IMHO, Neofetch's implementation really makes sense, and is tried and tested.
Let's do that.

**Comment by rashil2000** [comment]
It'll remove the additional overhead of modifying an extra file every time a new feature is added, and will make winfetch script truly independent. We can get rid of config.ps1 in this repo.

**Comment by jcwillox** [comment]
Yeah I have to agree. To be fair I don't think it's harder to edit a separate file, but otherwise yes.
Should we be keeping `-genconf`, it doesn't really have any purpose now?

**Comment by rashil2000** [comment]
I think we can repurpose genconf.
If a user somehow (there's not much to break as of now) messes up his config, the genconf can can reset it to the default.

**Comment by jcwillox** [comment]
Well they can just delete their config and it will be regenerated, otherwise, we will need to add a warning that `-genconf` will overwrite their config.

**Comment by rashil2000** [comment]
Yes, we can add the warning. It's really not possible to type -genconf by mistake, so I think we can assume that the user know what he's doing when he specifies that parameter.

Also, I don't think we need to output `Default config written ...`. It can do it silently (like Neofetch).

**Comment by jcwillox** [comment]
How does this look?
```pwsh
$Host.UI.PromptForChoice("Resetting your config to default will permanently delete it.", "Do you want to continue?", ("&Yes", "&No"), 1)
```
image

> Also, I don't think we need to output `Default config written ...`. It can do it silently (like Neofetch).

I know neofetch does it like that, but I think it can be helpful to let users know where the config is and that it exists, plus it only shows the first time they run it.

**Comment by rashil2000** [comment]
That's a nice idea. Make it 'overwrite it' instead of 'permanently delete it'. We're not technically deleting it.

**Comment by jcwillox** [comment]
Done, "literally" I do delete it, but I know what you mean 😄

**Comment by rashil2000** [comment]
But why? The command `Set-Content` is perfectly what you need, it overwrites content.

**Comment by rashil2000** [comment]
image

I think you should add (one line) descriptions here too, otherwise it shows blanks if I use the `?` option.

**Comment by jcwillox** [comment]
Done! let me know if you are happy for me to merge this.

image

image

**Comment by rashil2000** [comment]
All good to go!

However, should we wait for #55 to get merged first? Otherwise that will have conflicts.

**Comment by jcwillox** [comment]
Great, either way there will be conflicts I'd rather handle them on that PR.

**Pull request merged**
