### PR TITLE
Remove ImageMagick dependency

### PR DESCRIPTION
**Pull request by rashil2000**
This PR introduces substantial quality improvements, with very little code change.

Highlights:
- Speed. This one just _blows ImageMagick out of the water_. Testing on an extremely high res image (12000x6000), see below:

image

- Image quality. Better color reproduction and sharper outlines. See below:

image

- And of course, zero external dependencies from now on 🚀

### CODE REVIEW

**Comment by jcwillox** [comment]
Fantastic, I knew there'd be a way to do this without an external tool just never got around to looking into it. I'll test out the changes tonight 👍

**Comment by rashil2000** [comment]
Sure. 

I'll list out one issue I found. It seems to print an extra black/white line at the bottom of the image in rare cases. I'll have to dig deeper into that.

**Comment by jcwillox** [comment]
Gave it a try and it works pretty well, much faster compared to imagemagick. I did notice that issue you were talking about, but for me it's actually on every image, the bottom row of pixels is all white. Also, winfetch doesn't appear to work at all in PSv5, I get the following error,
```
+                 $currline += "$backVT$foreVTâ–„$e[0m"
+                                                ~~
Unexpected token '$e' in expression or statement.
```

**Comment by rashil2000** [comment]
Wait, that's weird, I do all my testing on PSv5. I don't even have 7.1 installed 😅

**Comment by jcwillox** [comment]
Indeed replacing that character with `$([char]0x2584)` fixed it, which is basically what they did in the original version with the `$CHAR` variable.

I've also figured out what the issue was with the white line, basically the character your using `▄` means the topmost pixel uses the background color, and pixels are printed 2 at a time, if `$ROWS` is not a multiple of 2 then it needs to print a single pixel on the last line, to do this you set the background color correctly and set the foreground color to nothing, causing to it print a white pixel on the bottom row.

To fix that you need to rewrite your logic to use `▀` instead (which is what they used in the original method), this is pretty straightforward, just change the block character and swap your background and foreground colors.

**Comment by rashil2000** [comment]
I made the change. Let me know if it works.

**Comment by jcwillox** [comment]
Yep tested and it's working fine.

**Pull request merged**
