### PR TITLE
Use "#" instead of "L".

### PR DESCRIPTION
**Pull request by Digital39999**
Why not use # which looks much better than "l"?

### CODE REVIEW

**Comment by rashil2000** [comment]
What's the reason for this?

**Comment by Digital39999** [comment]
It doesn't look bad

**Comment by rashil2000** [comment]
The logo was added by a contributor - likely after being generated via ASCII art generator. There's no need to change it unless there's a very strong reason, like if it hampers readability or something.

**Comment by Digital39999** [comment]
How can you even generate such ascii art if there's no windows character

**Pull request closed without merging**
