### PR TITLE
Handle image conversions

### LINKED ISSUE #18: Using image causes flickering display and freezes Windows
Exactly as the title said. I was curious about it, so I decided to try `winfetch` with `-image` pointing to [this](https://vignette.wikia.nocookie.net/logopedia/images/0/08/Windows_%282001%29.svg/revision/latest/scale-to-width-down/175?cb=20170723123925) image. `winfetch` appears to freeze, then after a little bit Windows freezes, then my display starts flickering in and out. Until I get freaked out and quickly terminate `winfetch`.

### LINKED ISSUE #46: Image mode extremely limited
The image mode seems to work nicely only for images that have width around 35px (=$COLUMNS). 

For others, it produces mostly extremely inaccurate representation of the image.

Screenshot (60)

One solution for this is to just resize the image (like the commands in screenshot above) on-the-fly.

### PR DESCRIPTION
**Pull request by rashil2000**
Closes #46
Potentially closes #18 too

Before:

image

After: 

image

### CODE REVIEW

**Comment by jcwillox** [comment]
I've actually just written a fix for the images as well, the issue was in the parsing of the output from ImageMagick. Check out #48, I think it's a better solution.

**Comment by rashil2000** [comment]
I had opened the issue some time ago, you should've suggested your idea there, or even better, here itself. Opening a separate PR after 15 minutes, is well, not cool. We gotta communicate.

**Comment by jcwillox** [comment]
I agree we need to communicate, however, that issue was only created a few hours ago and I'd already written the code before I saw your PR, and was about to open my own. I came across your solution of converting the image twice in my testing as well, but I was able to identify the root issue and solve that. So I created a separate PR as my solution was quite different from yours, what else would I do paste my code in the comments?. Sorry, I can see that might be annoying, and I really wasn't trying to be rude, of course, we want to work collaboratively but in certain circumstances, it's better to create a PR that supersedes another.

**Comment by rashil2000** [comment]
Agreed, your solution is better as it avoids conversion multiple times. 

We can use the Discussion forum as I mentioned earlier, that's what it's for :)

**Comment by jcwillox** [comment]
Thanks 😃, would you be ok with closing this PR, and testing out my solution?
Yes definitely a very interesting feature they've added, I'd be eager to try it out.

**Pull request closed without merging**
