### PR TITLE
Add motherboard, battery and IP information

### PR DESCRIPTION
**Pull request by jcwillox**
Adds `motherboard`, `battery`, `local_ip` and `public_ip` info lines.

I decided to make these additions one PR as the four new info lines are quite straightforward changes, but I'm happy to break it up too.

### CODE REVIEW

**Comment by rashil2000** [comment]
@jcwillox May I suggest adding slightly more information in the battery section? Like this: `Battery: 46% (Plugged in, charging)` and `Battery: 56% (Discharging)`. For plugged in and charging status, you can use similar CimSession commands. See how I implemented it in oh-my-posh for reference https://github.com/JanDeDobbeleer/oh-my-posh/blob/master/Helpers/Prompt.ps1#L231

**Comment by jcwillox** [comment]
@rashil2000 yep great idea, I was thinking of adding something like that but couldn't decide on a style. The style you suggested looks good I'll update the PR to include it.

**Comment by rashil2000** [comment]
@jcwillox Also, the Public IP section doesn't work. Furthermore, `Resolve-DNSName` command is only available in PowerShell version 5.1 and below. 

The output of `Resolve-DnsName -Name myip.opendns.com -Server resolver1.opendns.com | Format-List *` on my PC is this, which as you can see, does not contain any field named IPAddress.

```
QueryType              : SOA
Administrator          : noc.opendns.com
PrimaryServer          : auth1.opendns.com
NameAdministrator      : noc.opendns.com
SerialNumber           : xxxxxxxxxx
TimeToZoneRefresh      : 16384
TimeToZoneFailureRetry : 2048
TimeToExpiration       : 1048576
DefaultTTL             : 2560
Name                   : opendns.com
Type                   : SOA
CharacterSet           : Unicode
Section                : Authority
DataLength             : 108
TTL                    : 1273
```

Consider using something basic like `(Invoke-WebRequest -UseBasicParsing ifconfig.me/ip).Content`. Tested and working on all PowerShell versions; even on Ubuntu!

**Comment by jcwillox** [comment]
@rashil2000 I've added a fallback method to web requests for the public IP, so it should work now.
As for the extended battery info, in my testing, I've noticed that there are quite a few edge cases to take care of so I'll handle this properly in another PR in the future.

@kiedtl this PR should be complete now, ready for your final review, let me know if there's anything else to be done.

**Comment by rashil2000** [comment]
@jcwillox Could you tell me what edge cases are there? The oh-my-posh repo I referenced handles all edges and has been properly tested for various scenarios.

**Comment by jcwillox** [comment]
@rashil2000 fixed it 👍 . Basically, the issue was windows doesn't seem to provide me with the `TimeToFullCharge` property, and when switching between, charging and discharging it takes a bit for windows to provide the predicted battery life. Anyways upon revisiting the code I was able to create a working version. I still can't seem to get `TimeToFullCharge`, but in that case, it just won't show that.

**Pull request merged**
