### PR TITLE
New CPU Usage Retrieval and Process Counting Method

### PR DESCRIPTION
**Pull request by Carterpersall**
Implements a new method of CPU usage retrieval and process counting using .NET

- Uses `[diagnostics.process]::GetProcesses()` to get all running processes
  - Iterates through every process, and converts their CPU time to total CPU utilization using the logical processor count and a timespan of the current time and the processes' StartTime, and adds it to a total
    - I'm not exactly sure how this works yet
- Seems to be surprisingly accurate, but hard to test to what degree though due to CPU usage being quite volatile at small timescales
  - Likely accurate enough for this use case
- Might have some more room for optimization, but it is hard to tell as the tracer I use can't seem to decide what is the heaviest part of the process

- Gets the process count using the variable assigned to the output of `[diagnostics.process]::GetProcesses()`

Speed:
- PowerShell 5:
  - 1035ms → 177.2ms
    - 5.8x Faster
- PowerShell 7:
  - 1035ms → 27.18ms
    - 38x Faster

Bottlenecked Speed:
- PowerShell 5:
  - 1086ms → 658.76ms
    - 1.65x Faster
- PowerShell 7:
  - 1073ms → 121.75ms
    - 8.8x Faster

### CODE REVIEW

**Comment by rashil2000** [comment]
I'm seeing very significant performance regression on cold cache (5.5s vs 2.1s). Most users run winfetch once (during shell startup, or once during a demo etc.), so the cache will always remain cold. 

On warmer cache (repeated runs), there is improvement (1.0s vs 1.6s).

**Comment by Carterpersall** [comment]
Might be best to go back to the drawing board on this implementation then. There may not be a way to avoid the WMI call here, but there might be a way to improve speed in other places.

**Comment by rashil2000** [comment]
Hmm, marking as a draft for now.

**Comment by Carterpersall** [comment]
I'm currently working on quite a cool solution that gets all running processes and adds together their collective CPU usage. My testing so far has shown that the returned value is accurate while only taking ~80ms

**Comment by rashil2000** [comment]
Very interesting!

**Comment by rashil2000** [comment]
Hmm, I see. I've made a slight tweak, this looks good to go now.

**Pull request merged**
