### PR TITLE
Add current weather info

### PR DESCRIPTION
**Pull request by rashil2000**

### CODE REVIEW

**Comment by jcwillox** [comment]
Looking good, is there any reason you didn't use their formatting API, in my testing I found it was actually 2x faster, then retrieving the full JSON response.

```pwsh
(Invoke-RestMethod wttr.in/?format="%t+-+%C+(%l)").TrimStart("+")
```

I know you know this, but as a general PSA we should be careful switching to/using `http`, while in this case, we're not transmitting any location data / identifiable information so we don't necessarily need `https`, but if we did start using location information from the computer we would need to switch this to `https`.

**Comment by rashil2000** [comment]
The formatting API looks good, however, there is a subtle difference in location preciseness. My PR shows _local area and region_, whereas the command you mentioned shows _region and country_. This obviously allows for closer location-pointing. However, if the speed difference is really huge, we can sacrifice on that precision.

As for `http`, most sites usually have a redirect setup, to the corresponding `https` URI, but as I see in this case, while `ipconfig.me` redirects it, `wttr.in` does not. It's really only syntactic convenience at this point.

I'm open to suggestions, regarding both.

**Comment by jcwillox** [comment]
Yeah, I noticed that location thing too, it's up to you whether you want to use the JSON way or the formatting API, they both seem to produce the same weather info at least, however, I did notice about 630ms improvement with the formatting API.

**Comment by rashil2000** [comment]
I ended up favoring speed instead of precision.

Thanks for the suggestion!

**Pull request merged**
