### PR TITLE
Add pause command for disabling automatic closing.

### PR DESCRIPTION
**Pull request by rahmanlar**

### CODE REVIEW

**Comment by rashil2000** [comment]
...but, why?

**Comment by jcwillox** [comment]
I don't understand why we would want or need this. Also, that's a really bad way to implement it, PowerShell has its own method for pausing, why would you call an external shell just to pause.

**Comment by rashil2000** [comment]
@rahmanlar Would you like to elaborate? You haven't even given a description.

**Comment by rashil2000** [comment]
Closing due to lack of author feedback

**Pull request closed without merging**
