### PR TITLE
Add legacy Windows logo

### PR DESCRIPTION
**Pull request by rashil2000**
image

### CODE REVIEW

**Comment by jcwillox** [comment]
Very nice logo, I think I might actually prefer it 😮. Is it meant to be blinking? I think it'd be better if it was static, especially for people who prefer "reduced motion". In case that wasn't intensional you can disable the blinking by replacing `5;` with `1;` in the logo.

Also, you should add the parameter to the default config below `$noimage` and add a comment explaining what it does. E.g.

```pwsh
# $noimage = $true

# Use legacy windows logo
# $legacy = $true
```

You might want to rename the parameter, I think `-legacy` might be a bit vague, people could think you're talking about enabling legacy features, something like `-legacylogo` is much more explicit. If you use `legacylogo` you probably wouldn't even need a comment to explain what it does.

**Comment by rashil2000** [comment]
> Is it meant to be blinking?

Grab a cookie, you just discovered an easter egg 😁 
It was intentional; I just wanted to give a spin to an otherwise old logo.

Most terminals don't show the blinking - conhost (default), ConsoleZ, mintty, alacritty, ConEmu, Fluent Terminal, VSCode etc. 
Only Windows Terminal does.

**Comment by jcwillox** [comment]
Wow, interesting, it seems like having it **not** blink then would be the best default, and would be consistent amongst other terminals, and have better accessibility. We could make it optional to enable the blinking via another command-line or config option, e.g. `$blinking`, `$blinkinglogo`, `$noblinking` or `$DisableBlinking`, in the case of the last two we would ideally default to `$true`, it would be simple enough to implement with something like `$img.Replace("[1;", "[5;")`

**Comment by rashil2000** [comment]
Good call, I've disabled it by default.

**Comment by jcwillox** [comment]
Awesome, I like the way you did the blink option, we could use it elsewhere to control blinking if we ever wanted to.

**Pull request merged**
